In [2]:
import numpy as np

In [3]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[5, 3, 2], [1, 0, 0]])
X

array([[5, 3, 2],
       [1, 0, 0]])

In [4]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [5]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([5, 1])

In [7]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([1, 0, 0])

Soal 2

In [8]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [9]:
X_pt = torch.tensor([[5, 3, 2], [1, 0, 0]])
X_pt

tensor([[5, 3, 2],
        [1, 0, 0]])

In [10]:
X_pt.shape

torch.Size([2, 3])

In [11]:
X_pt[:,0]

tensor([5, 1])

In [12]:
X_pt[1,:]

tensor([1, 0, 0])

In [14]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [15]:
X_tf = tf.Variable([[5, 3, 2], [1, 0, 0]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[5, 3, 2],
       [1, 0, 0]], dtype=int32)>

In [16]:
X_tf.shape

TensorShape([2, 3])

In [17]:
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1], dtype=int32)>

In [18]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 0], dtype=int32)>