Soal 1

In [2]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([[0],
              [1],
              [0]])
x

array([[0],
       [1],
       [0]])

In [ ]:
# hitung nilai L2 norm dari vector x
(3**2 + 0**2 + 5**2)

Soal 2

In [16]:
# buat vector v dengan elemen (3,4)
v = np.array([[3],
              [4]])
v

array([[3],
       [4]])

In [17]:
# hitung nilai L2 norm dari vector v
(5**3 + 2**2)

129

In [18]:
# tampilkan unit vector dari vector v
norm = np.linalg.norm(v)
unit_v = v / norm
unit_v

array([[0.6],
       [0.8]])

In [19]:
# hitung panjang unit vector dari vector v
np.linalg.norm(unit_v)

np.float64(1.0)